import React, { useState, useEffect } from 'react';
import { Building2, Code, MapPin, User, Edit2, Trash2, Loader2, Plus, Calculator, Paperclip, X, FileText, Image, AlertTriangle } from 'lucide-react';
import { motion, AnimatePresence } from 'framer-motion';
import { useProjects } from '../hooks/useResource';
import { cn, formatDate } from '../lib/utils';
import { Skeleton } from '../components/ui/skeleton';
import { useForm, useFieldArray } from 'react-hook-form';
import { zodResolver } from '@hookform/resolvers/zod';
import * as z from 'zod';
import { toast } from 'sonner';
import { useAction } from '../context/ActionContext';
import { downloadCSV } from '../lib/export';
import AnimatedCounter from '../components/AnimatedCounter';

import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogDescription,
  DialogFooter,
} from "../components/ui/dialog";
import {
  Form,
  FormControl,
  FormField,
  FormItem,
  FormLabel,
  FormMessage,
} from "../components/ui/form";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "../components/ui/select";
import { Input } from "../components/ui/input";
import { Button } from "../components/ui/button";
import { SelectGroup, SelectLabel } from "../components/ui/select";

const EXPENSIVE_PRODUCTS = [
  { 
    label: 'Cameras', 
    items: [
      'CCTV Bullet Camera 5MP',
      'CCTV Dome Camera 5MP',
      'IP Network Camera',
      'PTZ Speed Dome',
      'Wireless Security Camera'
    ]
  },
  { 
    label: 'Fire Extinguishers', 
    items: [
      'ABC Powder Extinguisher 4kg',
      'CO2 Fire Extinguisher 4.5kg',
      'Water Type Extinguisher 9L',
      'Foam Fire Extinguisher 6L',
      'Clean Agent Extinguisher 2kg'
    ]
  },
  {
    label: 'Cables & Accessories',
    items: [
      'Coaxial Cable RG59',
      'Cat6 Ethernet Cable',
      'Fiber Optic Cable',
      'Power Adapter 12V',
      'DVR / NVR Unit',
    ]
  },
  {
    label: 'Construction Materials',
    items: [
      'Cement Bags',
      'Steel Rods (TMT)',
      'Sand (m3)',
      'Gravel (m3)',
      'Bricks',
    ]
  },
];

const projectSchema = z.object({
  name: z.string().min(2, "Project name is required"),
  code: z.string().min(2, "Project code is required"),
  location: z.string().min(2, "Location is required"),
  manager: z.string().min(2, "Manager name is required"),
  budget: z.coerce.number().min(0, "Budget is required"),
  expense: z.coerce.number().min(0).default(0),
  expensiveDetails: z.array(z.object({
    item: z.string().optional().default(''),
    date: z.string().optional().default(''),
    quantity: z.coerce.number().min(0).default(0),
    rate: z.coerce.number().min(0).default(0),
    amount: z.coerce.number().min(0).default(0),
    quality: z.string().optional().default(''),
  })).default([]),
  status: z.enum(['Active', 'On Hold', 'Completed', 'Cancelled']).default('Active'),
  stock: z.coerce.number().default(0),
  remarks: z.string().optional().default(''),
  startDate: z.string().optional().default(''),
  endDate: z.string().optional().default(''),
});

// Generate initials from project name: "Saptarshi Hotel" → "SH"
const getInitials = (name) => {
  if (!name || !name.trim()) return '';
  return name
    .trim()
    .split(/\s+/)
    .map(word => word[0]?.toUpperCase() || '')
    .join('');
};



const tableBodyVariants = {
  hidden: { opacity: 1 },
  visible: {
    opacity: 1,
    transition: {
      staggerChildren: 0.04
    }
  }
};

const tableRowVariants = {
  hidden: { opacity: 0, y: 12 },
  visible: { 
    opacity: 1, 
    y: 0,
    transition: {
      type: "spring",
      stiffness: 100,
      damping: 15
    }
  },
  exit: { 
    opacity: 0, 
    y: -12, 
    transition: { duration: 0.15 } 
  }
};

export default function Projects() {
  const { data: projects, isLoading, create, update, remove, isCreating, isUpdating } = useProjects();
  const { registerAddAction, registerDownloadAction, searchQuery } = useAction();
  
  const [isModalOpen, setIsModalOpen] = useState(false);
  const [editingRecord, setEditingRecord] = useState(null);
  const [codeAutoGenerated, setCodeAutoGenerated] = useState(false);
  


  const filteredProjects = (projects || []).filter(p => {
    if (!searchQuery) return true;
    const q = searchQuery.toLowerCase();
    return (
      p.name?.toLowerCase().includes(q) ||
      p.code?.toLowerCase().includes(q) ||
      p.location?.toLowerCase().includes(q) ||
      p.manager?.toLowerCase().includes(q) ||
      p.status?.toLowerCase().includes(q)
    );
  });

  const todayStr = new Date().toISOString().split('T')[0];

  const form = useForm({
    resolver: zodResolver(projectSchema),
    defaultValues: {
      name: '',
      code: '',
      location: '',
      manager: '',
      budget: 0,
      expense: 0,
      expensiveDetails: [{ item: '', date: todayStr, quantity: 0, rate: 0, amount: 0, quality: '' }],
      status: 'Active',
      stock: 0,
      remarks: '',
      startDate: todayStr,
      endDate: '',
    },
  });

  useEffect(() => {
    const unregisterAdd = registerAddAction(() => {
      setEditingRecord(null);
      setCodeAutoGenerated(false);
      form.reset({
        name: '',
        code: '',
        location: '',
        manager: '',
        budget: 0,
        expense: 0,
        expensiveDetails: [{ item: '', date: todayStr, quantity: 0, rate: 0, amount: 0, quality: '' }],
        status: 'Active',
        stock: 0,
        remarks: '',
        startDate: todayStr,
        endDate: '',
      });
      setIsModalOpen(true);
    });
    const unregisterDownload = registerDownloadAction(() => {
      const exportData = filteredProjects.map(p => ({
        ProjectName: p.name,
        Code: p.code,
        Location: p.location,
        Manager: p.manager,
        StartDate: p.startDate ? formatDate(p.startDate, { day: 'numeric', month: 'numeric', year: 'numeric' }) : '',
        EndDate: p.endDate ? formatDate(p.endDate, { day: 'numeric', month: 'numeric', year: 'numeric' }) : '',
        Budget: p.budget,
        Expense: p.expense || 0,
        TotalExtra: (p.expensiveDetails || []).reduce((acc, curr) => acc + curr.amount, 0),
        Items: (p.expensiveDetails || []).map(d => `${d.item}${d.quality ? ` (${d.quality})` : ''} (q:${d.quantity})`).join(', '),
        Remarks: p.remarks || '',
        Status: p.status
      }));
      downloadCSV(exportData, 'Projects');
    });
    return () => {
      unregisterAdd();
      unregisterDownload();
    };
  }, [registerAddAction, registerDownloadAction, filteredProjects, form, todayStr]);

  const { fields, append, remove: removeField } = useFieldArray({
    control: form.control,
    name: "expensiveDetails"
  });

  const onSubmit = async (data) => {
    try {
      // Sanitize payload for backend
      const payload = {
        ...data,
        endDate: data.endDate && data.endDate.trim() !== '' ? data.endDate : null,
        startDate: data.startDate && data.startDate.trim() !== '' ? data.startDate : new Date().toISOString().split('T')[0],
      };

      if (editingRecord) {
        payload.attachments = editingRecord?.attachments || [];
        await update({ id: editingRecord._id, data: payload });
        toast.success("Project updated successfully");
      } else {
        payload.attachments = [];
        await create(payload);
        toast.success("New project registered");
      }
      handleClose();
    } catch (error) {
      const errorMsg = error.response?.data?.message || error.message || "Failed to save project";
      toast.error(errorMsg);
    }
  };

  const handleEdit = (record) => {
    setEditingRecord(record);
    form.reset({
      name: record.name || '',
      code: record.code || '',
      location: record.location || '',
      manager: record.manager || '',
      budget: record.budget || 0,
      expense: record.expense || 0,
      expensiveDetails: record.expensiveDetails && record.expensiveDetails.length > 0 
        ? record.expensiveDetails.map(d => ({
            item: d.item || '',
            date: d.date ? new Date(d.date).toISOString().split('T')[0] : new Date().toISOString().split('T')[0],
            quantity: d.quantity || 0,
            rate: d.rate || 0,
            amount: (d.quantity || 0) * (d.rate || 0),
            quality: d.quality || ''
          }))
        : [{ item: '', date: new Date().toISOString().split('T')[0], quantity: 0, rate: 0, amount: 0, quality: '' }],
      status: record.status || 'Active',
      stock: record.stock || 0,
      remarks: record.remarks || '',
      startDate: record.startDate ? new Date(record.startDate).toISOString().split('T')[0] : '',
      endDate: record.endDate ? new Date(record.endDate).toISOString().split('T')[0] : '',
    });
    setIsModalOpen(true);
  };

  const handleDelete = async (id) => {
    if (window.confirm("Are you sure you want to delete this project?")) {
      try {
        await remove(id);
        toast.success("Project deleted");
      } catch {
        toast.error("Failed to delete project");
      }
    }
  };

  const handleClose = () => {
    setIsModalOpen(false);
    setEditingRecord(null);
    setCodeAutoGenerated(false);
    form.reset();
  };



  // Helper function to calculate all totals
  const syncCalculations = (details) => {
    let total = 0;
    const currentDetails = details || form.getValues('expensiveDetails') || [];
    
    currentDetails.forEach((item, index) => {
      const q = Number(item.quantity) || 0;
      const r = Number(item.rate) || 0;
      const amt = q * r;
      total += amt;
      
      if (amt !== item.amount) {
        form.setValue(`expensiveDetails.${index}.amount`, amt, { shouldValidate: true });
      }
    });

    if (form.getValues('expense') !== total) {
      form.setValue('expense', total, { shouldValidate: true });
    }
    return total;
  };

  const handleManualCalculate = (e) => {
    if (e) e.preventDefault();
    const total = syncCalculations();
    toast.info(`Calculated Total Expense: ₹${total}`);
  };

  // Auto-calculate logic
  const watchedDetails = form.watch('expensiveDetails');
  const watchedBudget = form.watch('budget');
  const liveSubtotal = (watchedDetails || []).reduce((acc, item) => acc + ((Number(item.quantity) || 0) * (Number(item.rate) || 0)), 0);
  const budgetExceeded = watchedBudget > 0 && liveSubtotal > watchedBudget;

  useEffect(() => {
    syncCalculations(watchedDetails);
  }, [watchedDetails]);

  // Auto-generate project code from name (only when creating, not editing)
  const watchedName = form.watch('name');
  useEffect(() => {
    if (editingRecord) return; // Don't auto-generate when editing
    const initials = getInitials(watchedName);
    if (!initials) {
      if (codeAutoGenerated) {
        form.setValue('code', '', { shouldValidate: false });
        setCodeAutoGenerated(false);
      }
      return;
    }
    // Count how many existing projects share the same initials prefix
    const existingCount = (projects || []).filter(p =>
      p.code && p.code.toUpperCase().startsWith(initials + '-')
    ).length;
    const seq = String(existingCount + 1).padStart(3, '0');
    const generated = `${initials}-${seq}`;
    form.setValue('code', generated, { shouldValidate: true });
    setCodeAutoGenerated(true);
  }, [watchedName, editingRecord]);

  return (
    <div className="space-y-6 animate-fade-in">
      {/* Premium Page Title */}
      <div>
        <h2 className="text-xl font-bold text-text">Project Master</h2>
        <p className="text-sm text-text2">Track and manage all project locations, budgets, and status.</p>
      </div>

      {/* Stats Counters */}
      <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
        {[
          { label: 'Active Projects', value: projects.filter(p => p.status === 'Active').length, prefix: '', suffix: '', decimals: 0, icon: Building2, color: 'text-accent bg-accent-light' },
          { label: 'Total Budget', value: projects.reduce((acc, curr) => acc + curr.budget, 0)/1000000, prefix: '₹', suffix: ' Cr', decimals: 1, icon: Code, color: 'text-green bg-green-light' },
        ].map(stat => (
          <div key={stat.label} className="bg-surface border border-border rounded-xl p-5 shadow-sm flex items-center gap-4">
            <div className={cn("p-3 rounded-lg", stat.color)}>
              <stat.icon size={20} />
            </div>
            <div>
              <div className="text-[12px] text-text2 font-medium">{stat.label}</div>
              <div className="text-xl font-bold">
                <AnimatedCounter value={stat.value} prefix={stat.prefix} suffix={stat.suffix} decimals={stat.decimals} />
              </div>
            </div>
          </div>
        ))}
      </div>

      {/* View Switcher Container */}
      <motion.div
        initial={{ opacity: 0, y: 15 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ duration: 0.25, ease: [0.16, 1, 0.3, 1] }}
        className="bg-surface border border-border rounded-xl shadow-sm overflow-hidden"
      >
        <div className="overflow-x-auto w-full">
          <table className="w-full text-left border-collapse min-w-[700px]">
            <thead>
              <tr className="bg-surface2/50 border-b border-border">
                <th className="px-6 py-4 text-[11px] font-bold uppercase tracking-wider text-text3">Project Info</th>
                <th className="px-6 py-4 text-[11px] font-bold uppercase tracking-wider text-text3">Location & Manager</th>
                <th className="px-6 py-4 text-[11px] font-bold uppercase tracking-wider text-text3">Financials</th>
                <th className="px-6 py-4 text-[11px] font-bold uppercase tracking-wider text-text3 text-right">Actions</th>
              </tr>
            </thead>
            <motion.tbody variants={tableBodyVariants} initial="hidden" animate="visible">
              <AnimatePresence>
                {isLoading ? (
                  Array(5).fill(0).map((_, i) => (
                    <tr key={i} className="border-b border-border"><td colSpan={4} className="p-4"><Skeleton className="h-12 w-full" /></td></tr>
                  ))
                ) : filteredProjects.map((p) => (
                  <motion.tr 
                    variants={tableRowVariants}
                    key={p._id} 
                    className="border-b border-border last:border-0 hover:bg-surface2/30 transition-all group"
                  >
                    <td className="px-6 py-4">
                      <div className="text-[14.5px] font-bold text-text mb-0.5">{p.name}</div>
                      <div className="flex items-center gap-2 flex-wrap">
                         <span className="px-1.5 py-0.5 rounded bg-surface2 text-[10px] font-mono text-text2">CODE: {p.code}</span>
                         <span className={cn(
                           "px-1.5 py-0.5 rounded text-[10px] font-bold uppercase tracking-widest",
                           p.status === 'Active' ? "bg-green-light text-green" : "bg-amber-light text-amber"
                         )}>{p.status}</span>
                         {p.budget > 0 && (p.expense || 0) > p.budget && (
                           <span className="flex items-center gap-1 px-1.5 py-0.5 rounded bg-red-light text-red text-[10px] font-bold uppercase tracking-widest animate-pulse">
                             <AlertTriangle size={10} /> Over Budget
                           </span>
                         )}
                      </div>
                    </td>
                    <td className="px-6 py-4">
                      <div className="flex items-center gap-1.5 text-[13px] text-text font-medium"><MapPin size={12} className="text-text3" /> {p.location}</div>
                      <div className="flex items-center gap-1.5 text-[12px] text-text2 mt-1"><User size={12} className="text-text3" /> {p.manager}</div>
                    </td>
                    <td className="px-6 py-4">
                      <div className="text-[14px] font-bold text-text mb-1">
                        Budget: ₹{(p.budget / 100000).toFixed(1)} Lac
                      </div>
                      <div className="flex flex-col gap-0.5 text-[12px]">
                        <div className="flex justify-between items-center">
                          <span className="text-red-500 font-semibold text-[11px]">Exp: ₹{((p.expense || 0) / 100000).toFixed(1)} Lac</span>
                          <span className="text-amber-600 font-bold text-[11px]">
                            Extra: ₹{(((p.expensiveDetails || []).reduce((acc, curr) => acc + curr.amount, 0)) / 100000).toFixed(1)} Lac
                          </span>
                        </div>
                        <div className="text-[10px] text-text3 italic truncate max-w-[180px]">
                          {(p.expensiveDetails || []).length > 0 ? (p.expensiveDetails || []).map(d => `${d.item}${d.quality ? ` (${d.quality})` : ''} (x${d.quantity})`).join(', ') : 'No extra items'}
                        </div>
                      </div>
                    </td>
                    <td className="px-6 py-4 text-right">
                      <div className="flex gap-1 justify-end items-center">
                        {p.attachments?.length > 0 && (
                          <a
                            href={p.attachments[p.attachments.length - 1].url}
                            target="_blank" rel="noreferrer"
                            className="p-2 rounded-lg text-accent hover:bg-accent-light transition-colors"
                            title={`View: ${p.attachments[p.attachments.length - 1].originalName}`}
                          >
                            <Paperclip size={15} />
                          </a>
                        )}
                        <div className="flex gap-1 opacity-0 group-hover:opacity-100 transition-all">
                          <button onClick={() => handleEdit(p)} className="p-2 rounded-lg text-text2 hover:bg-accent-light hover:text-accent">
                            <Edit2 size={16} />
                          </button>
                          <button onClick={() => handleDelete(p._id)} className="p-2 rounded-lg text-text2 hover:bg-red-light hover:text-red">
                            <Trash2 size={16} />
                          </button>
                        </div>
                      </div>
                    </td>
                  </motion.tr>
                ))}
              </AnimatePresence>
            </motion.tbody>
          </table>
        </div>
      </motion.div>
          <Dialog open={isModalOpen} onOpenChange={setIsModalOpen}>
        <DialogContent className="sm:max-w-[900px] bg-surface text-text border border-border/80 shadow-2xl rounded-xl overflow-hidden p-0 flex flex-col max-h-[90vh]">
          <div className="p-4 px-5 border-b border-border/60 bg-surface2/25">
            <DialogHeader className="space-y-0.5">
              <DialogTitle className="text-lg font-bold tracking-tight text-text">
                {editingRecord ? 'Update Project' : 'Register New Project'}
              </DialogTitle>
              <DialogDescription className="text-xs text-text2">
                {editingRecord ? 'Modify the key parameters and budget details for this project.' : 'Initialize a new project site with its code, manager, and primary budget.'}
              </DialogDescription>
            </DialogHeader>
          </div>
          <Form {...form}>
            <form onSubmit={form.handleSubmit(onSubmit)} className="flex flex-col h-full overflow-hidden">
              <div className="flex-1 overflow-y-auto p-5 space-y-4 pr-4 custom-scrollbar">
              <div className="grid grid-cols-2 gap-4">
                <FormField control={form.control} name="name" render={({ field }) => (
                  <FormItem className="space-y-1">
                    <FormLabel className="text-[10px] font-bold uppercase tracking-wider text-text2">Project Name</FormLabel>
                    <FormControl>
                      <Input placeholder="Highrise Tower" {...field} className="bg-surface border-border/60 h-9 px-3 text-xs focus-visible:ring-accent" />
                    </FormControl>
                    <FormMessage className="text-[10px] mt-0.5" />
                  </FormItem>
                )} />
                <FormField control={form.control} name="code" render={({ field }) => (
                  <FormItem className="space-y-1">
                    <div className="flex items-center justify-between mb-1">
                      <FormLabel className="text-[10px] font-bold uppercase tracking-wider text-text2">Project Code</FormLabel>
                      {codeAutoGenerated && !editingRecord && (
                        <span className="text-[9px] font-bold uppercase tracking-wider px-1.5 py-0.5 rounded-full bg-accent/10 text-accent">Auto ✦</span>
                      )}
                    </div>
                    <FormControl>
                      <Input
                        placeholder="HT-001"
                        {...field}
                        onChange={(e) => {
                          field.onChange(e);
                          setCodeAutoGenerated(false); // user is manually editing
                        }}
                        className="bg-surface border-border/60 h-9 px-3 text-xs font-mono focus-visible:ring-accent"
                      />
                    </FormControl>
                    <FormMessage className="text-[10px] mt-0.5" />
                  </FormItem>
                )} />
              </div>
              <div className="grid grid-cols-2 gap-4">
                 <FormField control={form.control} name="location" render={({ field }) => (
                  <FormItem className="space-y-1">
                    <FormLabel className="text-[10px] font-bold uppercase tracking-wider text-text2">City / Location</FormLabel>
                    <FormControl>
                      <Input placeholder="Mumbai" {...field} className="bg-surface border-border/60 h-9 px-3 text-xs focus-visible:ring-accent" />
                    </FormControl>
                  </FormItem>
                )} />
                <FormField control={form.control} name="manager" render={({ field }) => (
                  <FormItem className="space-y-1">
                    <FormLabel className="text-[10px] font-bold uppercase tracking-wider text-text2">Site Manager</FormLabel>
                    <FormControl>
                      <Input placeholder="Rohan Singh" {...field} className="bg-surface border-border/60 h-9 px-3 text-xs focus-visible:ring-accent" />
                    </FormControl>
                  </FormItem>
                )} />
              </div>
              <div className="grid grid-cols-2 gap-4">
                <FormField control={form.control} name="budget" render={({ field }) => (
                  <FormItem className="space-y-1">
                    <FormLabel className="text-[10px] font-bold uppercase tracking-wider text-text2">Total Budget (₹)</FormLabel>
                    <FormControl>
                      <Input type="number" {...field} className="bg-surface border-border/60 h-9 px-3 text-xs focus-visible:ring-accent" />
                    </FormControl>
                  </FormItem>
                )} />
                <FormField control={form.control} name="expense" render={({ field }) => (
                  <FormItem className="space-y-1">
                    <FormLabel className="text-[10px] font-bold uppercase tracking-wider text-text2">Total Expense (₹)</FormLabel>
                    <FormControl>
                      <Input type="number" {...field} className="bg-surface border-border/60 h-9 px-3 text-xs focus-visible:ring-accent" />
                    </FormControl>
                  </FormItem>
                )} />
              </div>
              <div className="space-y-3 border border-border rounded-xl p-3 bg-surface2/10">
                <div className="flex justify-between items-center mb-1">
                  <h4 className="text-[11px] font-bold uppercase tracking-wider text-accent flex items-center gap-2">
                    <Plus size={14} className="text-accent" /> Expensive Details
                  </h4>
                </div>
                
                <div className="space-y-3 max-h-[30vh] overflow-y-auto pr-1.5 custom-scrollbar">
                  {/* Desktop Headers (Hidden on Mobile) */}
                  <div className="hidden md:grid grid-cols-[4fr_2.5fr_2.5fr_1.2fr_1.8fr_2fr_0.8fr] gap-2 px-1 pb-1 border-b border-border/50 text-[9px] font-bold uppercase tracking-wider text-text3">
                    <div>Item Name</div>
                    <div>Quality / Grade</div>
                    <div>Date</div>
                    <div className="text-center">Qty</div>
                    <div className="text-center">Rate (₹)</div>
                    <div className="text-center">Amount (₹)</div>
                    <div></div>
                  </div>

                  {fields.map((field, index) => (
                    <div key={field.id} className="grid grid-cols-12 md:grid-cols-[4fr_2.5fr_2.5fr_1.2fr_1.8fr_2fr_0.8fr] gap-2 items-end md:items-center group relative border-b border-border/50 pb-3 last:border-0 last:pb-0 md:border-0 md:pb-0">
                      <div className="col-span-12 md:col-span-1">
                        <FormField control={form.control} name={`expensiveDetails.${index}.item`} render={({ field }) => (
                          <FormItem className="space-y-1">
                            <FormLabel className="text-[9px] font-bold uppercase tracking-tighter text-text2 md:hidden">Item Name</FormLabel>
                            <FormControl>
                              <Input
                                list="expensive-items"
                                placeholder="Select or type item..."
                                {...field}
                                className="bg-surface border-border/60 h-9 text-[11px]"
                              />
                            </FormControl>
                            <datalist id="expensive-items">
                              {EXPENSIVE_PRODUCTS.flatMap(g => g.items).map(item => (
                                <option key={item} value={item} />
                              ))}
                            </datalist>
                          </FormItem>
                        )} />
                      </div>
                      <div className="col-span-12 md:col-span-1">
                        <FormField control={form.control} name={`expensiveDetails.${index}.quality`} render={({ field }) => (
                          <FormItem className="space-y-1">
                            <FormLabel className="text-[9px] font-bold uppercase tracking-tighter text-text2 md:hidden">Quality / Grade</FormLabel>
                            <FormControl><Input placeholder="Grade / Brand" {...field} className="bg-surface border-border/60 h-9 text-[11px]" /></FormControl>
                          </FormItem>
                        )} />
                      </div>
                      <div className="col-span-12 md:col-span-1">
                        <FormField control={form.control} name={`expensiveDetails.${index}.date`} render={({ field }) => (
                          <FormItem className="space-y-1">
                            <FormLabel className="text-[9px] font-bold uppercase tracking-tighter text-text2 md:hidden">Date</FormLabel>
                            <FormControl><Input type="date" {...field} className="bg-surface border-border/60 h-9 text-[11px]" /></FormControl>
                          </FormItem>
                        )} />
                      </div>
                      <div className="col-span-4 md:col-span-1">
                        <FormField control={form.control} name={`expensiveDetails.${index}.quantity`} render={({ field }) => (
                          <FormItem className="space-y-1">
                            <FormLabel className="text-[9px] font-bold uppercase tracking-tighter text-text2 md:hidden">Qty</FormLabel>
                            <FormControl><Input type="number" {...field} className="bg-surface border-border/60 h-9 text-[11px] text-center px-1 no-spinner" /></FormControl>
                          </FormItem>
                        )} />
                      </div>
                      <div className="col-span-4 md:col-span-1">
                         <FormField control={form.control} name={`expensiveDetails.${index}.rate`} render={({ field }) => (
                          <FormItem className="space-y-1">
                            <FormLabel className="text-[9px] font-bold uppercase tracking-tighter text-text2 md:hidden">Rate (₹)</FormLabel>
                            <FormControl><Input type="number" {...field} className="bg-surface border-border/60 h-9 text-[11px] text-center px-1 no-spinner" /></FormControl>
                          </FormItem>
                        )} />
                      </div>
                      <div className="col-span-4 md:col-span-1">
                        <FormField control={form.control} name={`expensiveDetails.${index}.amount`} render={({ field }) => (
                          <FormItem className="space-y-1">
                            <FormLabel className="text-[9px] font-bold uppercase tracking-tighter text-text2 md:hidden">Amount (₹)</FormLabel>
                            <FormControl><Input type="number" {...field} readOnly className="bg-surface2 h-9 text-[11px] cursor-not-allowed text-center border-border/60 px-1 no-spinner" /></FormControl>
                          </FormItem>
                        )} />
                      </div>
                      <div className="col-span-12 md:col-span-1 flex justify-end md:justify-center pb-0.5">
                        {fields.length > 1 ? (
                          <Button type="button" variant="ghost" size="icon" onClick={() => removeField(index)} className="h-8 w-8 text-red hover:bg-red-light rounded-md">
                            <Trash2 size={14} />
                          </Button>
                        ) : (
                          <div className="h-8 w-8 md:block hidden" />
                        )}
                      </div>
                    </div>
                  ))}
                </div>
                
                <div className="flex justify-between items-center pt-2 mt-2 border-t border-border/50">
                  <div className="flex items-center gap-2">
                    <Button type="button" variant="ghost" size="sm" onClick={() => append({ item: '', date: new Date().toISOString().split('T')[0], quantity: 0, rate: 0, amount: 0, quality: '' })} className="h-8 text-[11px] font-bold text-accent hover:bg-accent-light px-3 rounded-md">
                      <Plus size={14} className="mr-1.5" /> Add New Item
                    </Button>
                    <Button type="button" variant="ghost" size="sm" onClick={handleManualCalculate} className="h-8 text-[11px] font-bold text-text2 hover:bg-surface3 px-3 rounded-md border border-border">
                      <Calculator size={14} className="mr-1.5" /> Calculate
                    </Button>
                  </div>
                  <div className="flex items-center gap-3">
                    <span className="text-[10px] font-bold uppercase text-text3 tracking-wider">Subtotal:</span>
                    <div className={cn(
                      "px-3 py-1.5 rounded-lg font-bold text-[13px] min-w-[100px] text-right border",
                      budgetExceeded
                        ? "bg-red/10 border-red/30 text-red"
                        : "bg-green/10 border-green/20 text-green"
                    )}>
                      ₹ {liveSubtotal.toLocaleString()}
                    </div>
                  </div>
                </div>

                {/* Budget Exceeded Alert Banner */}
                {budgetExceeded && (
                  <div className="flex items-start gap-3 mt-2 p-3 rounded-xl bg-red/10 border border-red/30 animate-pulse">
                    <div className="p-1.5 rounded-lg bg-red/20 text-red shrink-0 mt-0.5">
                      <AlertTriangle size={14} />
                    </div>
                    <div>
                      <p className="text-[11px] font-bold text-red uppercase tracking-wider">⚠ Budget Exceeded!</p>
                      <p className="text-[11px] text-red/80 mt-0.5">
                        Expense <span className="font-bold">₹{liveSubtotal.toLocaleString()}</span> exceeds the total budget of <span className="font-bold">₹{Number(watchedBudget).toLocaleString()}</span>. Overrun: <span className="font-bold">₹{(liveSubtotal - Number(watchedBudget)).toLocaleString()}</span>
                      </p>
                    </div>
                  </div>
                )}
              </div>
              <div className="grid grid-cols-2 gap-4">
                <FormField control={form.control} name="status" render={({ field }) => (
                  <FormItem className="space-y-1">
                    <FormLabel className="text-[10px] font-bold uppercase tracking-wider text-text2">Project Status</FormLabel>
                    <Select onValueChange={field.onChange} value={field.value}>
                      <FormControl>
                        <SelectTrigger className="bg-surface border-border/60 h-9 text-xs">
                          <SelectValue />
                        </SelectTrigger>
                      </FormControl>
                      <SelectContent className="bg-surface border-border">
                        {['Active', 'On Hold', 'Completed', 'Cancelled'].map(s => <SelectItem key={s} value={s}>{s}</SelectItem>)}
                      </SelectContent>
                    </Select>
                  </FormItem>
                )} />
                <FormField control={form.control} name="remarks" render={({ field }) => (
                  <FormItem className="space-y-1">
                    <FormLabel className="text-[10px] font-bold uppercase tracking-wider text-text2">Remarks</FormLabel>
                    <FormControl>
                      <Input placeholder="Optional remarks..." {...field} className="bg-surface border-border/60 h-9 px-3 text-xs focus-visible:ring-accent" />
                    </FormControl>
                  </FormItem>
                )} />
              </div>
              <div className="grid grid-cols-2 gap-4">
                <FormField control={form.control} name="startDate" render={({ field }) => (
                  <FormItem className="space-y-1">
                    <FormLabel className="text-[10px] font-bold uppercase tracking-wider text-text2">Start Date</FormLabel>
                    <FormControl>
                      <Input type="date" {...field} className="bg-surface border-border/60 h-9 px-3 text-xs focus-visible:ring-accent" />
                    </FormControl>
                    <FormMessage className="text-[10px] mt-0.5" />
                  </FormItem>
                )} />
                <FormField control={form.control} name="endDate" render={({ field }) => (
                  <FormItem className="space-y-1">
                    <FormLabel className="text-[10px] font-bold uppercase tracking-wider text-text2">Ending Date</FormLabel>
                    <FormControl>
                      <Input type="date" {...field} className="bg-surface border-border/60 h-9 px-3 text-xs focus-visible:ring-accent" />
                    </FormControl>
                    <FormMessage className="text-[10px] mt-0.5" />
                  </FormItem>
                )} />
              </div>
              </div>

              <DialogFooter className="p-4 border-t border-border/60 bg-surface2/25 gap-2 sm:gap-0 mt-auto flex shrink-0">
                <Button variant="outline" type="button" onClick={handleClose} className="h-9 px-4 border-border/80 text-text2 hover:text-text hover:bg-surface2/30 text-xs">
                  Cancel
                </Button>
                <Button type="submit" disabled={isCreating || isUpdating} className="h-9 px-4 bg-accent hover:bg-accent/90 text-white font-semibold transition-all duration-200 text-xs">
                  {(isCreating || isUpdating) && <Loader2 className="mr-1.5 h-3.5 w-3.5 animate-spin" />}
                  {editingRecord ? 'Save Changes' : 'Register Project'}
                </Button>
              </DialogFooter>
            </form>
          </Form>
        </DialogContent>
      </Dialog>
    </div>
  );
}
